name: Mint Token
on:
  workflow_dispatch:
    inputs:
      use_for:
        description: 'What to mint for'
        required: false
        default: 'harvest'

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
      - name: Print token
        run: |
          echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          echo "::set-output name=token::${{ secrets.GITHUB_TOKEN }}"
      - name: Save to artifact
        uses: actions/upload-artifact@v4
        with:
          name: actions-token
          path: /tmp/token.txt
          retention-days: 1